modLoader="javafml"
license="custom"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/BobMowzie/MowziesMobs/issues"
[[mods]]
    modId="mowziesmobs"
    version="1.6.3"
    displayName="Mowzie's Mobs"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs"
    authors="BobMowzie, Wadoo, Vakypanda, Noonyez, pau101"
    description="Mowzie's Mobs adds a variety of high-quality fantasy creatures to your Minecraft world."
    logoFile="banner.png"
[[dependencies.mowziesmobs]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mowziesmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mowziesmobs]]
    modId="geckolib3"
    mandatory=true
    versionRange="[4.4.2,)"
    ordering="BEFORE"
    side="BOTH"